title: César Cornejo # your name (or website title) here
logo: "/images/perfil-circ.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student, Computer Science Department, University of Rio Cuarto and CONICET -  

  <br><br>
  <a href=mailto:ccornejo@dc.exa.unrc.edu.ar"><img src="images/mail.jpeg" 
    width="32"
    height="22"/></a>
   <!-- Include style sheets -->
    <link rel="stylesheet" href="main.css" />

    <!-- Fonts from Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;600&display=swap" rel="stylesheet" />

    <!-- Load FontAwesome (for icons) -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
    />

    <!-- Load Academicons (for more icons) -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.2/css/academicons.min.css"
      integrity="sha512-KlJCpRsLf+KKu2VQa5vmRuClRFjxc5lXO03ixZt82HZUk41+1I0bD8KBSA0fY290ayMfWYI9udIqeOWSu1/uZg=="
      crossorigin="anonymous"
    />

 



theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
plugins:
  - jemoji
  - jekyll-remote-theme
