title: César Cornejo # your name (or website title) here
logo: "/images/perfil-circ.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student, Computer Science Department, University of Rio Cuarto and CONICET -  

  <br><br>
  <a href=mailto:ccornejo@dc.exa.unrc.edu.ar"><img src="images/mail.jpeg" 
    width="32"
    height="22"/></a>
  <link rel="stylesheet" href="academicons-1.9.4/academicons.min.css"/>


  <ul class="icons">
        <li>
          <a href="" title="Institutional website"><i class="fas fa-university"></i></a>
        </li>
        <li>
          <a href="" title="E-Mail"><i class="fas fa-envelope"></i></a>
        </li>
        <li>
          <a href="" title="GitHub"><i class="fab fa-github"></i></a>
        </li>
        <li>
          <a href="" title="LinkedIn"><i class="fab fa-linkedin"></i></a>
        </li>
        <li>
          <a href="" title="NASA / ADS"><i class="ai ai-ads"></i></a>
        </li>
        <li>
          <a href="" title="Google Scholar"><i class="ai ai-google-scholar"></i></a>
        </li>
      </ul>

 



theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
plugins:
  - jemoji
  - jekyll-remote-theme
