title: César Cornejo # your name (or website title) here
logo: "/images/perfil-circ.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. in Computer Science, University of Rio Cuarto and CONICET -  

  <br><br>
  
  <!-- Include style sheets -->
    <link rel="stylesheet" href="main.css" />

    <!-- Fonts from Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;600&display=swap" rel="stylesheet" />

    <!-- Load FontAwesome (for icons) -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
    />

    <!-- Load Academicons (for more icons) -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.2/css/academicons.min.css"
      integrity="sha512-KlJCpRsLf+KKu2VQa5vmRuClRFjxc5lXO03ixZt82HZUk41+1I0bD8KBSA0fY290ayMfWYI9udIqeOWSu1/uZg=="
      crossorigin="anonymous"
    />

    <ul class="icons">
        <li>
          <a href="mailto:ccornejo@dc.exa.unrc.edu.ar" target="_blank" rel="noopener noreferrer" title="E-Mail"><i class="fas fa-envelope"></i></a>
        </li>
        <li>
          <a href="https://dblp.org/pid/189/6219.html" target="_blank" rel="noopener noreferrer" title="dblp"><i class="ai ai-dblp"></i></a>
        </li>
        <li>
          <a href="https://www.researchgate.net/profile/Cesar-Cornejo-5" target="_blank" rel="noopener noreferrer" title="ResearchGate"><i class="fab fa-researchgate"></i></a>
        </li>
        <li>
          <a href="https://scholar.google.com/citations?user=RWndQjwAAAAJ&hl=es&oi=ao" target="_blank" rel="noopener noreferrer" title="Google Scholar"><i class="ai ai-google-scholar"></i></a>
        </li>
        <li>
          <a href="https://github.com/cesarcorne" target="_blank" rel="noopener noreferrer" title="GitHub"><i class="fab fa-github"></i></a>
        </li>
        <li>
          <a href="https://dc.exa.unrc.edu.ar" target="_blank" rel="noopener noreferrer" title="Institutional website"><i class="fas fa-university"></i></a>
        </li>
    </ul>



theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
plugins:
  - jemoji
  - jekyll-remote-theme
